apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  type: ClusterIP
  selector:
    app: mysql

---
  apiVersion: v1
  kind: Service
  metadata: 
    name: redis
    labels: 
      app: "redis"
  spec: 
    ports: 
      - 
        name: redisport
        port: 6379
    type: ClusterIP
    selector: 
      app: redis
  
  
